# Generated by Django 4.0.1 on 2022-01-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
